### ISSUE TITLE
Unable to specify a location for the built package

### ISSUE THREAD

**Issue by alex-davidson** [roryprimrose/MsBuild.NuGet.Pack#17]
In version 1.6.1, setting `NugetPackageTargetDir` controlled only the working directory of `nuget.exe`, causing the package to be written to that directory. In version 2, this property appears to control the `-BasePath` parameter as well, so the package takes files from the wrong location.

Judging by the implementation of the BuildNuSpecTask, these can no longer be controlled individually:

```
ProcessStartInfo startInfo = new ProcessStartInfo(this.NuGetPath)
{
    Arguments = "pack \"" + this.NuSpecPath + "\" -OutputDirectory \"" + this.OutDir + " \" -BasePath \"" + this.OutDir + " \" -NoPackageAnalysis -NonInteractive -Verbosity Detailed",
    ...
    WorkingDirectory = this.OutDir
};
```

This seems to be incompatible with our build process, which publishes packages to an output folder rather than a server.

Was this an intentional change? Is there a workaround/correct approach for version 2.0, or should we continue to use 1.6.1?

**Comment by roryprimrose** [comment]
Can you describe the folder structure of your build process. 

The assumption here is that the nuspec is built by sourcing the binaries of the project from the project output path and writing the resulting nupkg file to the same location. 

I can't remember what triggered the change, but it could have been a change to the NuGet CLI when it was updated to 2.8.5.

**Comment by alex-davidson** [comment]
We define an output folder as an MSBuild property and write all output artifacts (packages, binaries, etc) to there. The output folder is not required to be part of the repository's folder hierarchy. This assists in making the build process agnostic to whether it's running on a CI server or a developer machine.

**Comment by roryprimrose** [comment]
I've pushed a change which you can test via [https://www.nuget.org/packages/MsBuild.NuGet.Pack/2.1.0-nuspecbasepath0001](https://www.nuget.org/packages/MsBuild.NuGet.Pack/2.1.0-nuspecbasepath0001).

You can now configure the nuspec base path using the [NuSpecBasePath](https://github.com/roryprimrose/MsBuild.NuGet.Pack/blob/3f135c3dc2b3572e239d4b67aa4a4568b4a976ec/MsBuild.NuGet.Pack/tools/MsBuild.NuGet.Pack.targets#L45) MsBuild property. This property will default to the output path unless you specify a value.

**Comment by alex-davidson** [comment]
Thanks, that's pretty close. I can now get the desired effect by explicitly setting NuSpecBasePath to the project's $(TargetDir) and then setting NugetPackageTargetDir to our output directory, but that requires either building each project individually or setting up each project file to override NuSpecBasePath.

By swapping around the initialisation/inheritance of NugetPackageTargetDir and NuSpecBasePath in the MsBuild.NuGet.Pack.targets file, I can simply specify NugetPackageTargetDir in the top-level build script and everything works perfectly:

    <NuSpecBasePath Condition="'$(NuSpecBasePath)' == ''">$(TargetDir)</NuSpecBasePath>
    <NugetPackageTargetDir Condition="'$(NugetPackageTargetDir)' == ''">$(NuSpecBasePath)</NugetPackageTargetDir>

Would this break other use cases, do you think?

**Comment by roryprimrose** [comment]
Are you not able to provide an MsBuild property to your build pipeline? TFS and VSTS support this in the build step where you can provide additional parameters that apply to the entire solution being compiled.

**Comment by alex-davidson** [comment]
Yes, however:
* NugetPackageTargetDir is the place to which we want the package written.
* NuSpecBasePath is where NuGet will look for files to put in the package.
* We're building multiple projects in one go, and each project will have it's own TargetDir.
* NuSpecBasePath needs to be the TargetDir of the project being packaged.
* NugetPackageTargetDir needs to be the output path, which is the constant output directory path we're trying to inject.
If NuSpecBasePath defaults to NugetPackageTargetDir, it's going to be wrong for every project unless we override it for each project individually.

**Comment by alex-davidson** [comment]
I suppose the tricky bit is not breaking existing scripts which expect NugetPackageTargetDir to control the source of files, too.
This PR #22 accomplishes exactly what we need, hopefully without breaking anyone else's build scripts!

**Comment by roryprimrose** [comment]
I've uploaded a new beta package at https://www.nuget.org/packages/MsBuild.NuGet.Pack/2.0.1-nuspecbasepath0005 if you can have a look.

**Comment by alex-davidson** [comment]
Excellent, this works perfectly with our build system now. Thank you!
