### ISSUE TITLE
Valid Version regex to match SemVer 1.0

### ISSUE THREAD

**Issue by o-o00o-o** [roryprimrose/MsBuild.NuGet.Pack#5]
Currently the valid version pattern match is ^\d+(.\d+){0,3}$

but this doesn't match what is actually allowed for nuget with semver

See the following
http://semver.org/spec/v1.0.0.html
http://blog.nuget.org/20140924/supporting-semver-2.0.0.html

Can we change it to be 

^\d+.\d+.\d+(-([a-zA-Z0-9-]+))?$ 

(untested, written freehand)
So it is testing for a proper semver v1.0 that nuget supports

I thought I could rewrite the assemblyinfo file to work around my earlier issue #4 but as this isn't supporting prerelease information (which is what I wanted) I'm going to have to work out a different way.

**Comment by roryprimrose** [comment]
Unfortunately this won't work. This is the reason why I wrote the fall-back to file version if the product version cannot be resolved to version parts. I'm also using GitVersion and this is the reason I hit.

For example, consider the following ProductVersion

```
2.0.8-mybranch.1+122.Branch.mybranch.Sha.a82f60255e9d9917a50d13717bbc33a42ebd583f
```

The FileVersionInfo returns all the product version values as 0. In this scenario, the FileVersion was 2.0.8.0 and so the parts get interpreted correctly using the fall-back logic.

The only way to move this forward would be to use pure regex to parse out the version parts from product version and fall back to file version where product version did not contain x.x.x or x.x.x.x where IncludeBuildVersion = True

**Comment by o-o00o-o** [comment]
I don't follow you. That example for ProductVersion _wouldn't_ match that pattern match as that Productversion is a valid v2 Semver not a valid v1 Semver.  My Semver regex was for if you provided a ProductVersion from the GitVersion_NugetVersion property, so for above would be something like:

2.0.8-mybranch00001

which is a valid nuget version and then would simply be used directly

I'm not sure if you had seen it but I did submit a pull request that contained fixes for both #4 and #5 that were both needed to allow this and it has been working well since then.

**Comment by o-o00o-o** [comment]
Perhaps I can clarify a bit further. 
- As things stand right nowwith GitVersion you really also need #4 to solve this. 

-- it may be that, in future, GitVersion will allow you to pick the attribute to inject into the ProductVersion (although in my case I would rather leave the v2 semver in ProductVersion and only use the GitVersion_NugetVersion for only the NugetVersion so using #4 to provide the GitVersion_NugetVersion and leaving GitVersion to populate the full GitVersion_InformationalVersion as the ProductVersion.
- But if not using GitVersion then the pattern match I suggested should be the one used as it would allow setting the Nuget Version directly .. with a prerelease part directly via your assemblyinfo.cs..

In both cases the Regex needs to changed to the one above to be able to pick this up correctly. If you are using traditional 4 part .net versions I don't know why you can't just allow the system to use the file/assembly version.. no need to use the ProductVersion at all?

**Comment by roryprimrose** [comment]
I've taken bits and pieces of the PR. Some of it was redundant because of #4 being implemented.
