### ISSUE TITLE
Add capability to pack -symbols

### ISSUE THREAD

**Issue by michaeljesse73-zz** [roryprimrose/MsBuild.NuGet.Pack#7]
If there is a way to add the "-symbols" option as part of a specific Compilation, such as Debug, that would be a great addition.

**Comment by roryprimrose** [comment]
Are you referring to the pdb files? They should be included by default.

**Comment by michaeljesse73-zz** [comment]
Based on what I understand and have used running the **nuget.exe**, to actually build a Symbols package, you need to add the `-symbols` option.

https://docs.nuget.org/Create/Creating-and-Publishing-a-Symbol-Package#creating-a-symbol-package

So the _BuildNuSpecTask.cs_ just needs to an overload for `Execute()` or perhaps a different Task altogether.

**Comment by roryprimrose** [comment]
Merging the nuspec with the project metadata uses [OutputFile].\* which should include the dll/exe and the pdb for the project. Are there other symbols you wanted included?

**Comment by michaeljesse73-zz** [comment]
Hmm, let me look at that task.  Maybe that's what I was missing.  I think when I wrote the question, I was just using the Build Task.

**Comment by roryprimrose** [comment]
Confirmed, the current implementation with the file extension wildcard puts all files with the same name as the project output assembly file name in the nupkg. This includes pdb and xml files where found.

**Comment by roryprimrose** [comment]
If you wanted to change this, you can add specific file elements to the nuspec.
